### ISSUE TITLE
Command is not executed if it echoing  something inside

### ISSUE THREAD

**Issue by yujin1st** [vova07/yii2-console-runner-extension#1]
If command has an echo "something" it stops executing...

**Comment by saada** [comment]
We need a way to capture the output of each command for web display

**Comment by Lexxtor** [comment]
Here is my hack to run commands:

```php
ob_start();
(new ToolController('', Yii::$app->module))->actionCleanAssets();
$output = nl2br(ob_get_clean());
```

**Comment by Ir00man** [comment]
@Lexxtor, and what is **ToolController** and its action **actionCleanAssets**?

**Comment by Lexxtor** [comment]
@Ir00man, ***ToolController*** is a console command controller. ***actionCleanAssets*** is it's action.

**Comment by Ir00man** [comment]
@Lexxtor, oh, you mean in "console command terminology" you run this way a **clean-assets** command, like we do via console: yii tool/clean-assets

And if need to pass some arguments, what you do?

And don't forget that the main difference between your variant and @vova07 extension is that his code call command in background.

**Comment by Lexxtor** [comment]
@Ir00man, yes.
May be like this, I can't tell it exactly, without looking into code...
```php
ob_start();
(new ToolController('', Yii::$app->module))->actionCleanAssets('argument value', 'another value');
$output = nl2br(ob_get_clean());
```
