### ISSUE TITLE
PHP-FMP Issue with PHP_BINARY

### ISSUE THREAD

**Issue by manky** [vova07/yii2-console-runner-extension#10]
When using php-fpm, PHP_BINARY returns php-fpm binary not php binary 

For example:
php-fpm: PHP_BINARY = /usr/sbin/php-fpm
php: PHP_BINARY = /usr/bin/php

I do believe is better to use old solution

$cmd = PHP_BINDIR . '/php ' . Yii::getAlias($this->file) . ' ' . $cmd;

instead of a new one

$cmd = PHP_BINARY . ' ' . Yii::getAlias($this->file) . ' ' . $cmd;

**Comment by vova07** [comment]
Was fixed in https://github.com/vova07/yii2-console-runner-extension/pull/12
Now you can specify your own file path for `php binary`.
Thanks!
