### ISSUE TITLE
PHP executable not found under Windows

### ISSUE THREAD

**Issue by GaryA** [vova07/yii2-console-runner-extension#5]
Due to a bug in PHP ( https://bugs.php.net/bug.php?id=61044&edit=1 ) PHP_BINDIR does not correctly point to the PHP executable under Windows, particularly when PHP is installed as part of XAMPP etc.
PHP_BINARY also does not work correctly under Windows (points to Apache httpd).

Perhaps the simplest workaround is to add another configuration parameter to point to php.exe when the OS is Windows. See https://github.com/GaryA/yii2-console-runner-extension

**Comment by vova07** [comment]
Should be solved by https://github.com/vova07/yii2-console-runner-extension/pull/2
